### ISSUE TITLE
design time webapi - question

### ISSUE THREAD

**Issue by Jacknq** [ZeekoZhu/TextTemplatingCore#3]
Nice work, thanks for your project. 
Could you provide DesignTime example of webapi template generating something? 
Im trying but its not yet succesfully.

**Comment by ZeekoZhu** [comment]
Hi, I pushed a new sample on the repo, check it out:[https://github.com/ZeekoZhu/TextTemplatingCore/blob/dev/samples/DesignTimeSample/Crud.tt](https://github.com/ZeekoZhu/TextTemplatingCore/blob/dev/samples/DesignTimeSample/Crud.tt)
And a problem in the parser has been fix just now, you can download a new version later

**Comment by ZeekoZhu** [comment]
here is a new version: https://www.myget.org/feed/zeekoget/package/nuget/TextTemplating.Tools

**Comment by Jacknq** [comment]
Great, thanks for new version. 
In that example I was interested how do you read all existing controllers, using reflection or apiexplorer to generate methods with parameters, let say easy example in json?

**Comment by ZeekoZhu** [comment]
I use ApiExplorer in the runtime templating example, but I don't think it is very useful. I guess the way that [https://github.com/domaindrivendev/Swashbuckle](https://github.com/domaindrivendev/Swashbuckle) uses is better, so I will update that example when I have more time.

**Comment by Jacknq** [comment]
Thanks. 
Swagger seems quite complex. 
Some time ago I came across https://gist.github.com/Gordon-Beeming/11166590 
 (aka hubs.tt which is excelent and flexible ) which I modified for my use with signalr in .net core..

So I was wondering how to do it analogically with webapi.
Integrated your excellent library in .net core. But for webapi seems not so many t4 examples out there.
Thanks for your effort.

**Comment by ZeekoZhu** [comment]
Actually, I have a plan to write a design time template to generate http client code with angular http, axios, jQuery ajax, that is why I port T4 to dotnet core

**Comment by Jacknq** [comment]
Yeah, I was there also but went from js to ts and vue.js as effective elegant solution with .net core...

**Comment by Jacknq** [comment]
Im on way creating one template using reflection. Might be later in my repo. Closing this one.
