### ISSUE TITLE
.net core 2.1 

### ISSUE THREAD

**Issue by Jacknq** [ZeekoZhu/TextTemplatingCore#5]
if I put 
` <TargetFramework>netcoreapp2.1</TargetFramework>`
template using
```xml
<#@ template debug="true" hostspecific="true" language="C#" #>
<#@ import namespace="Newtonsoft.Json" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ import namespace="System" #>
<#@ import namespace="System.IO" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="Microsoft.AspNetCore.Http" #>
<#@ import namespace="Microsoft.AspNetCore.Mvc" #>
<#@ import namespace="Microsoft.AspNetCore.Mvc.ApiExplorer" #>
<#@ import namespace="System.Reflection" #>
<#@ import namespace="Microsoft.AspNetCore.Mvc" #>
<#@ import namespace="System.Text.RegularExpressions" #>
<#@ import namespace="System.Threading.Tasks" #>
<#@ import namespace="System.Reflection" #>
<#@ import namespace="System.Runtime" #>
<#@ import namespace="System.Xml" #>
<#@ import namespace="System.Xml.Linq" #>
<#@ Assembly name="EnvDTE" #>
<#@ output extension=".ts" #>
```
although I have in .csproj (tried 4.1.1 with same result):
`<PackageReference Include="System.Collections" Version="4.3.0" />`

im getting following error on 2.1 core when trying to complie template that on .net core 2.0 works 
>Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Collections, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) ---> System.IO.FileLoadException: Could not load file or assembly 'System.Collections, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL'.

any helpfull ideas?

**Comment by ZeekoZhu** [comment]
I update this tool to dotnet core 2.1, please use https://www.myget.org/feed/zeekoget/package/nuget/TextTemplating.Tools/2.2.1-alpha1 . But T4 is really a out of date technology, please consider migrating to https://github.com/filipw/dotnet-script or https://github.com/daveaglick/Scripty

**Comment by Jacknq** [comment]
BIG thanks! 

Please note that not everybody is willing to rewrite big part of their T4 scripts, especially when this works on .net core, thanks to you again.  T4 is supported in latest VS2017, I dont see it necessary out of date. 

In terms of usability, yes there is Roslyn, and those promising projects. However I would like to see more advanced examples scripts, adoption and same elegance when it comes to switching between multi-line code and multi-line template text parts using opening and closing tags.. And or t4 to dotnet-script converter, excellent integration etc. etc.

**Comment by ZeekoZhu** [comment]
T4 to `dotnet-script` converter, that is a good idea, I'll have a try on it. :smile:

**Comment by Jacknq** [comment]
There are also T4 plugins for vscode and VS.. T4 is official format, new community projects are just trying to find right shape. I hope I ll see more of it solving complex problems.
But how about T4 to dotnet-script internally and getting output there, keeping syntax features. Just brainstorming.)
I would be happy if this project stays in tact with .net core versions.
